name: Build Windows EXE (PyInstaller)

on:
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with .spec if present
        shell: bash
        run: |
          if [ -f "GoogleFlowTool.spec" ]; then
            pyinstaller --clean --noconfirm GoogleFlowTool.spec
          else
            # fallback: build from main tool file
            pyinstaller --noconfirm --clean --windowed --name GoogleFlowTool flow_browser_tool.py
          fi

      - name: Upload artifact (folder)
        uses: actions/upload-artifact@v4
        with:
          name: GoogleFlowTool-dist
          path: dist/**
          if-no-files-found: error


